// Code generated by mockery v2.43.2. DO NOT EDIT.

package testdata

import mock "github.com/stretchr/testify/mock"

// ObtainMatchOrderCountUsecase is an autogenerated mock type for the ObtainMatchOrderCountUsecase type
type ObtainMatchOrderCountUsecase struct {
	mock.Mock
}

// Do provides a mock function with given fields:
func (_m *ObtainMatchOrderCountUsecase) Do() uint32 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Do")
	}

	var r0 uint32
	if rf, ok := ret.Get(0).(func() uint32); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint32)
	}

	return r0
}

// NewObtainMatchOrderCountUsecase creates a new instance of ObtainMatchOrderCountUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewObtainMatchOrderCountUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *ObtainMatchOrderCountUsecase {
	mock := &ObtainMatchOrderCountUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
