// Code generated by mockery v2.43.2. DO NOT EDIT.

package testdata

import (
	domain "orderprocessor/internal/order/domain"

	mock "github.com/stretchr/testify/mock"
)

// ObtainMaxMinPendingOrderUsecase is an autogenerated mock type for the ObtainMaxMinPendingOrderUsecase type
type ObtainMaxMinPendingOrderUsecase struct {
	mock.Mock
}

// Do provides a mock function with given fields:
func (_m *ObtainMaxMinPendingOrderUsecase) Do() *domain.UnmatchedOrderPrices {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Do")
	}

	var r0 *domain.UnmatchedOrderPrices
	if rf, ok := ret.Get(0).(func() *domain.UnmatchedOrderPrices); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UnmatchedOrderPrices)
		}
	}

	return r0
}

// NewObtainMaxMinPendingOrderUsecase creates a new instance of ObtainMaxMinPendingOrderUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewObtainMaxMinPendingOrderUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *ObtainMaxMinPendingOrderUsecase {
	mock := &ObtainMaxMinPendingOrderUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
