// Code generated by mockery v2.43.2. DO NOT EDIT.

package testdata

import (
	domain "orderprocessor/internal/order/domain"

	mock "github.com/stretchr/testify/mock"
)

// OrderMatchAndPersistUsecase is an autogenerated mock type for the OrderMatchAndPersistUsecase type
type OrderMatchAndPersistUsecase struct {
	mock.Mock
}

// Do provides a mock function with given fields: _a0
func (_m *OrderMatchAndPersistUsecase) Do(_a0 *domain.Order) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Do")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Order) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewOrderMatchAndPersistUsecase creates a new instance of OrderMatchAndPersistUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderMatchAndPersistUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderMatchAndPersistUsecase {
	mock := &OrderMatchAndPersistUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
